# Generated by Django 4.1 on 2022-10-11 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
