# Generated by Django 4.1 on 2022-10-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ems_backend", "0002_alter_employee_dob"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="dob",),
    ]
