# Generated by Django 4.1 on 2022-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_backend", "0003_remove_employee_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
