# Generated by Django 4.1 on 2022-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ems_backend",
            "0004_alter_employee_first_name_alter_employee_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
