# Generated by Django 4.1 on 2022-10-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ems_backend", "0005_alter_employee_first_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="first_name", new_name="firstName",
        ),
        migrations.RenameField(
            model_name="employee", old_name="last_name", new_name="lastName",
        ),
        migrations.RenameField(
            model_name="employee", old_name="middle_name", new_name="middleName",
        ),
    ]
